import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

import Sidebar from '@/components/Mixins/Sidebar/Sidebar';
import NavSidebar from '@/components/Mixins/Sidebar/NavSidebar';

const fontSans = FontSans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <main className="h-full">
          <div className="h-[80px] md:pl-60 fixed inset-y-0 w-full z-50">
            <NavSidebar />
          </div>
          <div className="fixed inset-y-0 z-50 flex-col hidden h-full md:flex w-60 bg-[#333333]">
            <Sidebar />
          </div>
          <section className="md:pl-60 pt-[80px] h-full bg-[#333333]">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
